//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVEHICLE
    {
        public string VEHICLE_ID { get; set; }
        public E_VH_TYPE VEHICLE_TYPE { get; set; }
        public int VEHICLE_ACC_DIST { get; set; }
        public int MANT_ACC_DIST { get; set; }
        public Nullable<System.DateTime> MANT_DATE { get; set; }
        public int GRIP_COUNT { get; set; }
        public int GRIP_MANT_COUNT { get; set; }
        public Nullable<System.DateTime> GRIP_MANT_DATE { get; set; }
        public Nullable<System.DateTime> LAST_FULLY_CHARGED_TIME { get; set; }
        public bool IS_INSTALLED { get; set; }
        public Nullable<System.DateTime> INSTALLED_TIME { get; set; }
        public Nullable<System.DateTime> REMOVED_TIME { get; set; }
    }
}
