//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    
    public enum E_TRAN_STATUS : int
    {
        Queue = 0,
        PreInitial = 1,
        Initial = 2,
        Transferring = 3,
        Canceling = 4,
        Aborting = 5,
        Canceled = 6,
        Aborted = 7,
        Complete = 8,
        RouteChanging = 9,
        Reject = 10
    }
}
