//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.mirle.ibg3k0.sc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OHTC_DevEntities : DbContext
    {
        public OHTC_DevEntities()
            : base("name=OHTC_DevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ABASEDATA_VER> ABASEDATA_VER { get; set; }
        public DbSet<ABLOCKZONEDETAIL> ABLOCKZONEDETAIL { get; set; }
        public DbSet<AGROUPRAILS> AGROUPRAILS { get; set; }
        public DbSet<AMAIN_VER> AMAIN_VER { get; set; }
        public DbSet<APOINT> APOINT { get; set; }
        public DbSet<ARAIL> ARAIL { get; set; }
        public DbSet<ASUB_VER> ASUB_VER { get; set; }
        public DbSet<BLOCKZONEQUEUE> BLOCKZONEQUEUE { get; set; }
        public DbSet<ABLOCKZONEMASTER> ABLOCKZONEMASTER { get; set; }
        public DbSet<ASEQUENCE> ASEQUENCE { get; set; }
        public DbSet<ACYCLEZONEDETAIL> ACYCLEZONEDETAIL { get; set; }
        public DbSet<ACYCLEZONEMASTER> ACYCLEZONEMASTER { get; set; }
        public DbSet<ACYCLEZONETYPE> ACYCLEZONETYPE { get; set; }
        public DbSet<ACEID> ACEID { get; set; }
        public DbSet<ARPTID> ARPTID { get; set; }
        public DbSet<ANETWORKQUALITY> ANETWORKQUALITY { get; set; }
        public DbSet<APORTICON> APORTICON { get; set; }
        public DbSet<BCSTAT> BCSTAT { get; set; }
        public DbSet<AEQPT> AEQPT { get; set; }
        public DbSet<ALINE> ALINE { get; set; }
        public DbSet<AZONE> AZONE { get; set; }
        public DbSet<ANODE> ANODE { get; set; }
        public DbSet<AUNIT> AUNIT { get; set; }
        public DbSet<ABUFFER> ABUFFER { get; set; }
        public DbSet<ACASSETTE> ACASSETTE { get; set; }
        public DbSet<ACRATE> ACRATE { get; set; }
        public DbSet<AECDATAMAP> AECDATAMAP { get; set; }
        public DbSet<AEVENTRPTCOND> AEVENTRPTCOND { get; set; }
        public DbSet<AFLOW_REL> AFLOW_REL { get; set; }
        public DbSet<UASFNC> UASFNC { get; set; }
        public DbSet<ALOT> ALOT { get; set; }
        public DbSet<HOPERATION> HOPERATION { get; set; }
        public DbSet<ASHEET> ASHEET { get; set; }
        public DbSet<HASHEET> HASHEET { get; set; }
        public DbSet<ATRACEITEM> ATRACEITEM { get; set; }
        public DbSet<ATRACESET> ATRACESET { get; set; }
        public DbSet<UASUSRGRP> UASUSRGRP { get; set; }
        public DbSet<UASUFNC> UASUFNC { get; set; }
        public DbSet<APORTSTATION> APORTSTATION { get; set; }
        public DbSet<APORT> APORT { get; set; }
        public DbSet<AMCSREPORTQUEUE> AMCSREPORTQUEUE { get; set; }
        public DbSet<AADDRESS_DATA> AADDRESS_DATA { get; set; }
        public DbSet<APARKZONEDETAIL> APARKZONEDETAIL { get; set; }
        public DbSet<APARKZONEMASTER> APARKZONEMASTER { get; set; }
        public DbSet<APARKZONETYPE> APARKZONETYPE { get; set; }
        public DbSet<APORT_POSITION_TEACHING_DATA> APORT_POSITION_TEACHING_DATA { get; set; }
        public DbSet<AVEHICLE_CONTROL_100> AVEHICLE_CONTROL_100 { get; set; }
        public DbSet<CONTROL_DATA> CONTROL_DATA { get; set; }
        public DbSet<SCALE_BASE_DATA> SCALE_BASE_DATA { get; set; }
        public DbSet<ASYSEXCUTEQUALITY> ASYSEXCUTEQUALITY { get; set; }
        public DbSet<AHIDZONEDETAIL> AHIDZONEDETAIL { get; set; }
        public DbSet<AHIDZONEMASTER> AHIDZONEMASTER { get; set; }
        public DbSet<AHIDZONEQUEUE> AHIDZONEQUEUE { get; set; }
        public DbSet<ALARMRPTCOND> ALARMRPTCOND { get; set; }
        public DbSet<ASECTION_CONTROL_100> ASECTION_CONTROL_100 { get; set; }
        public DbSet<VSECTION_100> VSECTION_100 { get; set; }
        public DbSet<ASECTION> ASECTION { get; set; }
        public DbSet<ASEGMENT> ASEGMENT { get; set; }
        public DbSet<AADDRESS> AADDRESS { get; set; }
        public DbSet<ALARM> ALARM { get; set; }
        public DbSet<UASUSR> UASUSR { get; set; }
        public DbSet<ACMD> ACMD { get; set; }
        public DbSet<ACMD_DETAIL> ACMD_DETAIL { get; set; }
        public DbSet<ATRANSFER> ATRANSFER { get; set; }
        public DbSet<ACARRIER> ACARRIER { get; set; }
        public DbSet<AVEHICLE> AVEHICLE { get; set; }
        public DbSet<HCMD> HCMD { get; set; }
        public DbSet<HTRANSFER> HTRANSFER { get; set; }
        public DbSet<AGROUPPORTSTATION> AGROUPPORTSTATION { get; set; }
        public DbSet<VTRANSFER> VTRANSFER { get; set; }
    }
}
